version: '1.0.{build}'

pull_requests:
  do_not_increment_build_number: true

image: Visual Studio 2017

clone_folder: C:\projects\cppmetrics

before_build:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - cd C:\projects\cppmetrics

build_script:
  - mkdir build
  - cd build
  - cmake -G "NMake Makefiles" .. -DBUILD_TESTS=1
  - nmake

test_script:
  - cd C:\projects\cppmetrics\build
  - nmake /A test

after_test:
  - ps: >-
      $url = "https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)";
      $wc = New-Object 'System.Net.WebClient';
      Get-ChildItem C:\projects\cppmetrics\build -Recurse -File -Include *_test_result.xml | % { echo $_.FullName; $wc.UploadFile($url, $_.FullName) }

on_failure:
  - ps: >-
      $url = "https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)";
      $wc = New-Object 'System.Net.WebClient';
      Get-ChildItem C:\projects\cppmetrics\build -Recurse -File -Include *_test_result.xml | % { echo $_.FullName; $wc.UploadFile($url, $_.FullName) }
